var tableData = [{
    "Acuerdo de tratamiendo arancelario": null,
    "Aduana": null,
    "Aduana de Exportación Anterior": null,
    "Aduana de la Declaración Anterior": null,
    "Agente Aduanero": null,
    "Código Partida": null,
    "Clase Importador": null,
    "Departamento del Importador": null,
    "Departamento Destino": null,
    "Depósito": null,
    "Embalaje": null,
    "Forma de pago": null,
    "Importador": null,
    "Lugar de ingreso": null,
    "Mes": null,
    "País de compra": null,
    "País de origen": null,
    "País de procedencia": null,
    "País del exportador": null,
    "Proveedor": null,
    "Régimen importación": null,
    "Tipo de declaración": null,
    "Tipo de importación": null,
    "Agencia transportadora": null,
    "Vía de transporte": null,
    "Arancel en USD": null,
    "Arancel pagado": null,
    "Base arancel": null,
    "Base de IVA": null,
    "Cantidad(es)": null,
    "IVA (USD)": null,
    "IVA Pagado": null,
    "Otros pagados": null,
    "Precio Unitario CIF (COP) Peso neto": null,
    "Precio Unitario CIF (USD) Cantidad Unidad Comercial": null,
    "Precio Unitario CIF (USD) Peso Bruto": null,
    "Precio Unitario CIF (USD) Peso Neto": null,
    "Precio Unitario FOB (USD) Cantidad Unidad Comercial": null,
    "Precio Unitario FOB (COP) Peso Bruto": null,
    "Precio Unitario CIF (COP) Peso Bruto": null,
    "Precio Unitario FOB (COP) Cantidad Unidad Comercial": null,
    "Precio Unitario CIF (COP) Cantidad Unidad Comercial": null,
    "Precio Unitario FOB (USD) Peso Neto": null,
    "Peso en kilos brutos": null,
    "Peso en kilos netos": null,
    "Porcentaje de arancel": null,
    "Porcentaje de IVA": null,
    "Precio Unitario FOB (USD) Peso Bruto": null,
    "Porcentaje de otros": null,
    "Total": null,
    "Total (USD)": null,
    "Total Pagado": null,
    "Tasa de cambio": null,
    "Valor CIF (USD)": null,
    "Valor seguro": null,
    "Valor Otros gastos": null,
    "Valor FOB (USD)": null,
    "Valor FOB (COP)": null,
    "Valor CIF (COP)": null,
    "Valor en Aduana": null
}]

export default {
    tableData
}