export var tableDataHeaders = [{
    "Acuerdo de tratamiendo arancelario": null,
    "Aduana": null,
    "Aduana de Exportación Anterior": null,
    "Aduana de la Declaración Anterior": null,
    "Agente Aduanero": null,
    "Código Partida": null,
    "Clase Importador": null,
    "Departamento del Importador": null,
    "Departamento Destino": null,
    "Depósito": null,
    "Embalaje": null,
    "Forma de pago": null,
    "Importador": null,
    "Lugar de ingreso": null,
    "Mes": null,
    "País de compra": null,
    "País de origen": null,
    "País de procedencia": null,
    "País del exportador": null,
    "Proveedor": null,
    "Régimen importación": null,
    "Tipo de declaración": null,
    "Tipo de importación": null,
    "Agencia transportadora": null,
    "Vía de transporte": null,
    "Arancel en USD": null,
    "Arancel pagado": null,
    "Base arancel": null,
    "Base de IVA": null,
    "Cantidad(es)": null,
    "IVA (USD)": null,
    "IVA Pagado": null,
    "Otros pagados": null,
    "Precio Unitario CIF (COP) Peso neto": null,
    "Precio Unitario CIF (USD) Cantidad Unidad Comercial": null,
    "Precio Unitario CIF (USD) Peso Bruto": null,
    "Precio Unitario CIF (USD) Peso Neto": null,
    "Precio Unitario FOB (USD) Cantidad Unidad Comercial": null,
    "Precio Unitario FOB (COP) Peso Bruto": null,
    "Precio Unitario CIF (COP) Peso Bruto": null,
    "Precio Unitario FOB (COP) Cantidad Unidad Comercial": null,
    "Precio Unitario CIF (COP) Cantidad Unidad Comercial": null,
    "Precio Unitario FOB (USD) Peso Neto": null,
    "Peso en kilos brutos": null,
    "Peso en kilos netos": null,
    "Porcentaje de arancel": null,
    "Porcentaje de IVA": null,
    "Precio Unitario FOB (USD) Peso Bruto": null,
    "Porcentaje de otros": null,
    "Total": null,
    "Total (USD)": null,
    "Total Pagado": null,
    "Tasa de cambio": null,
    "Valor CIF (USD)": null,
    "Valor seguro": null,
    "Valor Otros gastos": null,
    "Valor FOB (USD)": null,
    "Valor FOB (COP)": null,
    "Valor CIF (COP)": null,
    "Valor en Aduana": null
}]

export var tableDataDownload = {
    "Acuerdo de tratamiendo arancelario": "Acuerdo de tratamiendo arancelario",
    "Aduana": "Aduana",
    "Aduana de Exportación Anterior": "Aduana de Exportación Anterior",
    "Aduana de la Declaración Anterior": "Aduana de la Declaración Anterior",
    "Agente Aduanero": "Agente Aduanero",
    "Código Partida": "Código Partida",
    "Clase Importador": "Clase Importador",
    "Departamento del Importador": "Departamento del Importador",
    "Departamento Destino": "Departamento Destino",
    "Depósito": "Depósito",
    "Embalaje": "Embalaje",
    "Forma de pago": "Forma de pago",
    "Importador": "Importador",
    "Lugar de ingreso": "Lugar de ingreso",
    "Mes": "Mes",
    "País de compra": "País de compra",
    "País de origen": "País de origen",
    "País de procedencia": "País de procedencia",
    "País del exportador": "País del exportador",
    "Proveedor": "Proveedor",
    "Régimen importación": "Régimen importación",
    "Tipo de declaración": "Tipo de declaración",
    "Tipo de importación": "Tipo de importación",
    "Agencia transportadora": "Agencia transportadora",
    "Vía de transporte": "Vía de transporte",
    "Arancel en USD": "Arancel en USD",
    "Arancel pagado": "Arancel pagado",
    "Base arancel": "Base arancel",
    "Base de IVA": "Base de IVA",
    "Cantidad(es)": "Cantidad(es)",
    "IVA (USD)": "IVA (USD)",
    "IVA Pagado": "IVA Pagado",
    "Otros pagados": "Otros pagados",
    "Precio Unitario CIF (COP) Peso neto": "Precio Unitario CIF (COP) Peso neto",
    "Precio Unitario CIF (USD) Cantidad Unidad Comercial": "Precio Unitario CIF (USD) Cantidad Unidad Comercial",
    "Precio Unitario CIF (USD) Peso Bruto": "Precio Unitario CIF (USD) Peso Bruto",
    "Precio Unitario CIF (USD) Peso Neto": "Precio Unitario CIF (USD) Peso Neto",
    "Precio Unitario FOB (USD) Cantidad Unidad Comercial": "Precio Unitario FOB (USD) Cantidad Unidad Comercial",
    "Precio Unitario FOB (COP) Peso Bruto": "Precio Unitario FOB (COP) Peso Bruto",
    "Precio Unitario CIF (COP) Peso Bruto": "Precio Unitario CIF (COP) Peso Bruto",
    "Precio Unitario FOB (COP) Cantidad Unidad Comercial": "Precio Unitario FOB (COP) Cantidad Unidad Comercial",
    "Precio Unitario CIF (COP) Cantidad Unidad Comercial": "Precio Unitario CIF (COP) Cantidad Unidad Comercial",
    "Precio Unitario FOB (USD) Peso Neto": "Precio Unitario FOB (USD) Peso Neto",
    "Peso en kilos brutos": "Peso en kilos brutos",
    "Peso en kilos netos": "Peso en kilos netos",
    "Porcentaje de arancel": "Porcentaje de arancel",
    "Porcentaje de IVA": "Porcentaje de IVA",
    "Precio Unitario FOB (USD) Peso Bruto": "Precio Unitario FOB (USD) Peso Bruto",
    "Porcentaje de otros": "Porcentaje de otros",
    "Total": "Total",
    "Total (USD)": "Total (USD)",
    "Total Pagado": "Total Pagado",
    "Tasa de cambio": "Tasa de cambio",
    "Valor CIF (USD)": "Valor CIF (USD)",
    "Valor seguro": "Valor seguro",
    "Valor Otros gastos": "Valor Otros gastos",
    "Valor FOB (USD)": "Valor FOB (USD)",
    "Valor FOB (COP)": "Valor FOB (COP)",
    "Valor CIF (COP)": "Valor CIF (COP)",
    "Valor en Aduana": "Valor en Aduana"
}
